apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-service-configmap
data:
  DB_NAME: coworking_db
  DB_USER: david
  DB_HOST: postgresql-service
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
data:
  password: TVZPZ2Q1UVJpSHpvYmk2ag==